trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - release/*
      - hotfix/*
      - feature/*
  
pr:
  branches:
    include:
    - bug-fix/*
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: 01_variables.yml
  
name: build_and_test_solution
jobs:
  - job: build_and_test
    displayName: Build & test .NET Core solution
    steps:
    - template: 02_build_and_test.yml